version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres_SMIT:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
  
  app:
    build: .
    depends_on:
      - postgres
    restart: always
    ports:
      - "8000:8000"

volumes:
  postgres_SMIT: